[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
mantle_sepolia = "https://rpc.sepolia.mantle.xyz"

[etherscan]
mantle_sepolia = { key = "${ETHERSCAN_API_KEY}" }
